FROM trafex/php-nginx:2.5.0

# Install composer from the official image
COPY --from=composer /usr/bin/composer /usr/bin/composer

USER root

RUN apk add --no-cache \
  git \
  imagemagick \
  redis \
  php8-simplexml \
  php8-xmlwriter \
  php8-mbstring \
  php8-zip \
  php8-gettext \
  php8-soap \
  php8-pecl-imagick \
  php8-pecl-redis \
  php8-pecl-igbinary \
  php8-fileinfo \
  php8-iconv \
  php8-exif \
  php8-bcmath

RUN sed -i 's|/var/www/html|/var/www/app|g' /etc/nginx/nginx.conf

WORKDIR /var/www

USER nobody
